image: Ubuntu1804

stack: node 10

skip_tags: true

branches: 
  only: 
    - master
  except: 
    - gh-pages

skip_commits: 
  message: /#[Nn][Oo][Bb][Uu][Ii][Ll][Dd]/

version: 1.1.{build}

cache: 
  - node_modules

install:
  - node --version
  - npm --version
  - npm ci

before_build:
  - npm version $APPVEYOR_BUILD_VERSION --no-git-tag-version
  - echo version $APPVEYOR_BUILD_VERSION
  - sudo touch ".git-credentials"
  - git config --global credential.helper store --file=".git-credentials"
  - echo "https://${GITHUB_API_KEY}:x-oauth-basic@github.com" | sudo tee ".git-credentials" >> /dev/null
  - git config --global user.email appveyor@24sevenoffice.com
  - git config --global user.name tfso

build: sh
build_script:
  - npm run publish
  - npm run deploy