image: Ubuntu1804

stack: node 10

skip_tags: true

branches: 
  only: 
    - master
  except: 
    - gh-pages

skip_commits: 
  message: /#[Nn][Oo][Bb][Uu][Ii][Ll][Dd]/

version: 1.1.{build}

cache: 
  - node_modules

install:
  - node --version
  - npm --version
  - npm ci

before_build:
  - npm version $APPVEYOR_BUILD_VERSION --no-git-tag-version
  - echo version $APPVEYOR_BUILD_VERSION
  - git config user.email appveyor@24sevenoffice.com
  - git config user.name tfso

build: sh
  - npm run deploy
  - npm run publish