image: Visual Studio 2017

version: 1.1.{build}

environment:
  nodejs_version: "10"

branches: 
  only: 
    - master
  except: 
    - gh-pages

skip_tags: true

skip_commits: 
  message: /#[Nn][Oo][Bb][Uu][Ii][Ll][Dd]/

cache: 
  - node_modules

init:
  - git config --global credential.helper store
  - git config --global user.email appveyor@24sevenoffice.com
  - git config --global user.name tfso

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm ci
  # - touch ".git-credentials"
  - ps: Add-Content "$HOME\.git-credentials" "https://$($GITHUB_API_KEY):x-oauth-basic@github.com`n"
  # - echo "https://${GITHUB_API_KEY}:x-oauth-basic@github.com" | tee ".git-credentials" >> /dev/null

before_build:
  - echo version %APPVEYOR_BUILD_VERSION%
  - npm version %APPVEYOR_BUILD_VERSION% --no-git-tag-version

build: sh
build_script:
  - npm run build
  - publish-to-git --force --remote https://%GITHUB_API_KEY%:x-oauth-basic@github.com/%APPVEYOR_REPO_NAME%
  - npm run build:demo
  - gh-pages -d build -r https://%GITHUB_API_KEY%:x-oauth-basic@github.com/%APPVEYOR_REPO_NAME%