image: Visual Studio 2017

version: 1.1.{build}

environment:
  nodejs_version: "10"

branches: 
  only: 
    - master
  except: 
    - gh-pages

skip_tags: true

skip_commits: 
  message: /#[Nn][Oo][Bb][Uu][Ii][Ll][Dd]/

init:
  - git config --global user.email appveyor@24sevenoffice.com
  - git config --global user.name tfsobob

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm ci

before_build:
  - echo version %APPVEYOR_BUILD_VERSION%
  - npm version %APPVEYOR_BUILD_VERSION% --no-git-tag-version
  - npm run lint
  - npm run test

build: off
build_script:
  - npm run build
  - node_modules\.bin\publish-to-git --force --tag %APPVEYOR_BUILD_VERSION% --remote https://%GITHUB_API_KEY%:x-oauth-basic@github.com/%APPVEYOR_REPO_NAME%
  - npm run build:demo
  - node_modules\.bin\gh-pages -d build -r https://%GITHUB_API_KEY%:x-oauth-basic@github.com/%APPVEYOR_REPO_NAME%